name: Deploy Website

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - id: 'checkout'
      uses: 'actions/checkout@v3'

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        service_account: ${{ secrets.DEPLOY_SERVICE_ACCOUNT }}

    - id: 'upload-folder'
      uses: 'google-github-actions/upload-cloud-storage@v1'
      with:
        path: '/path/to/folder'
        destination: 'bucket-name'
